truncate table country;
commit;
truncate table products;
commit;
truncate table Employees;
commit;
TRUNCATE TABLE Orders;
COMMIT;
truncate table Customers;
commit;
truncate table simpledatatype;
commit;
truncate table debits;
commit;
TRUNCATE TABLE Region;
COMMIT;