CREATE OR REPLACE PROCEDURE "CustOrdersOrders"(VCUSTOMERID IN Orders.OrderID%TYPE := 1, CUR_OUT OUT PKGENTLIB_ARCHITECTURE.CURENTLIB_ARCHITECTURE)
	AS

BEGIN
    OPEN cur_OUT FOR
	SELECT *
	FROM Orders
	WHERE customerID = vCustomerId;
END;
/
