CREATE OR REPLACE PROCEDURE CustOrdersOrders(VCUSTOMERID IN Orders.CustomerID%TYPE := 1, CUR_OUT OUT PKGENTLIB_ARCHITECTURE.CURENTLIB_ARCHITECTURE)
	AS

BEGIN
    OPEN cur_OUT FOR
	SELECT
		OrderID,
		OrderDate,
		RequiredDate,
		ShippedDate
	FROM Orders
	WHERE CustomerID = vCustomerId;
END;
/
